version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: uv
    directory: /python
    schedule:
      interval: weekly
  - package-ecosystem: uv
    directory: /benchmarks
    schedule:
      interval: weekly
  - package-ecosystem: uv
    directory: /ci/benchmark
    schedule:
      interval: weekly
  - package-ecosystem: uv
    directory: /examples/python/qwen
    schedule:
      interval: weekly
